In [2]:
import numpy as np

In [3]:
lista = [1,2,3]

In [4]:
lista

[1, 2, 3]

In [5]:
np.array(lista)

array([1, 2, 3])

In [6]:
matriz = [[1,2,3], [4,5,6],[7,8,9]]

In [7]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
arr = np.zeros(3)

In [12]:
arr

array([0., 0., 0.])

In [13]:
arr = np.zeros((5,5))

In [14]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.linspace(0,10,2)

array([ 0., 10.])

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.random.rand(5)

array([0.74224117, 0.9080927 , 0.35373211, 0.32656467, 0.71598956])

In [22]:
np.random.rand(5) * 100

array([72.31298791, 44.18542842, 84.34111892, 51.3556848 , 50.45589019])

In [24]:
np.random.rand(5,4)

array([[0.09165977, 0.80499401, 0.37314967, 0.98592811],
       [0.04103149, 0.97195984, 0.19263866, 0.33879693],
       [0.85554515, 0.96262852, 0.7940451 , 0.38913595],
       [0.87768283, 0.92632941, 0.02026053, 0.52193047],
       [0.28568756, 0.55404186, 0.80206986, 0.37311292]])

In [26]:
np.random.rand(5,4, 3)

array([[[0.66308569, 0.4483454 , 0.98538937],
        [0.63919659, 0.66078389, 0.5314999 ],
        [0.34056584, 0.23058676, 0.87476025],
        [0.27892504, 0.01609806, 0.17150488]],

       [[0.73768697, 0.19832874, 0.23930964],
        [0.07061054, 0.89561692, 0.40938834],
        [0.03518003, 0.72685895, 0.45937563],
        [0.49750205, 0.39217015, 0.00120527]],

       [[0.59938739, 0.06109397, 0.33477132],
        [0.38698081, 0.77626957, 0.75017049],
        [0.71413162, 0.51597999, 0.05143056],
        [0.69186738, 0.43421747, 0.57905638]],

       [[0.20225006, 0.90130382, 0.3840738 ],
        [0.54943   , 0.31506616, 0.14496968],
        [0.77591539, 0.4764958 , 0.97170162],
        [0.58226193, 0.336651  , 0.87418228]],

       [[0.02070241, 0.00535078, 0.6230101 ],
        [0.59701603, 0.07460485, 0.34025714],
        [0.33078414, 0.6381291 , 0.99040224],
        [0.48512802, 0.53336311, 0.59252174]]])

In [28]:
np.random.randn(5)

array([ 0.60643549, -0.86088191, -0.61708947,  0.28557296,  0.78883595])

In [29]:
np.random.randint(0,100,10)

array([48, 54, 47, 47, 67,  7, 57, 70, 35, 98])